# This is a basic workflow to help you get started with Actions

name: Reservation bus

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reservation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependency
      - name: npm ci
        run: npm ci

      # Running reservation
      - name: npm run start
        run: npm run start
        env:
          MIRI_USER_EMAIL: ${{ secrets.MIRI_USER_EMAIL }}
          MIRI_USER_PASS: ${{ secrets.MIRI_USER_PASS }}
          REST_DATE_OPENAPI_KEY: ${{ secrets.REST_DATE_OPENAPI_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
          TARGET_BUS_NUM: 3000
          TARGET_BUS_TIME: "07:30"
          TARGET_START_STAT_ID: 01125
          TARGET_ARRIV_STAT_ID: 22997
          SEAT_PRIORITY: "[12,16,20,24,28,9,13,17,21,25,8,5,32,29,36,33,4,1,7,6,11,10,15,14,19,18,23,22,27,26,31,30,35,34,3,2,44,41,43,42]"
          TARGET_BUS_DATE: 2
